"""Bilingual labels owned by the book renderers.

Names, notes, dates, source text, event descriptions, and other Gramps content
remain in the language in which they were entered.
"""

from ..book_language import model_book_language

_LABELS = {
    "fr": {
        "family_history": "Histoire familiale",
        "dedication": "Dédicace",
        "introduction": "Introduction",
        "by": "Par : ",
        "contents": "Table des matières",
        "front_matter": "Avant-propos",
        "ancestry": "Ascendance",
        "descent": "Descendance",
        "documentary_appendix": "Annexe documentaire",
        "person_index": "Index des personnes",
        "family_notices": "Notices familiales",
        "person_profiles": "Fiches individuelles",
        "family_connections": "Liens familiaux",
        "family_details": "Détails de la famille",
        "family": "Famille",
        "family_section": "Section familiale",
        "generation": "Génération",
        "branch": "Branche",
        "children": "Enfants",
        "partners": "Partenaires",
        "children_and_parentage": "Enfants et filiations",
        "and": " et ",
        "see": "Voir",
        "first_appearance": "première apparition dans la généalogie",
        "view_profile": "Voir la fiche",
        "view_first_mention": "Voir la première mention",
        "generation_navigation": "Navigation des générations",
        "browse_generations": "Parcourir les générations",
        "individual_profile": "Notice individuelle",
        "events": "Événements",
        "notes": "Notes",
        "sources": "Sources",
        "references": "Références",
        "repositories": "Dépôts",
        "urls": "URL",
        "media": "Médias",
        "featured_image": "Image mise en avant",
        "reproduction_unavailable": "reproduction indisponible",
        "full_page_reproduction": "Reproduction en pleine page :",
        "page_abbreviation": "p.",
        "author": "Auteur",
        "publication_date": "Date de publication",
        "reference_family": "Famille de référence",
        "intermediate_model": "personnes dans le modèle intermédiaire.",
        "skip_to_content": "Aller au contenu principal",
        "couple_portraits": "Portraits du couple",
        "portrait_of": "Portrait de",
        "document": "Document",
        "document_image_no_description": "Image documentaire sans description",
        "see_reproduction": "Voir la reproduction :",
        "document_reference": "Référence documentaire",
        "role": "Rôle",
        "filiation": "filiation",
        "gramps_identifiers": "Identifiants Gramps",
        "citation": "citation",
        "source": "source",
        "owner_person": "personne",
        "owner_family": "famille",
        "owner_event": "événement",
        "owner_note": "note",
        "owner_media": "média",
        "owner_citation": "citation",
        "book_title_fallback": "Livre généalogique",
    },
    "en": {
        "family_history": "Family history",
        "dedication": "Dedication",
        "introduction": "Introduction",
        "by": "By: ",
        "contents": "Contents",
        "front_matter": "Front matter",
        "ancestry": "Ancestry",
        "descent": "Descent",
        "documentary_appendix": "Documentary appendix",
        "person_index": "Person index",
        "family_notices": "Family notices",
        "person_profiles": "Person profiles",
        "family_connections": "Family connections",
        "family_details": "Family details",
        "family": "Family",
        "family_section": "Family section",
        "generation": "Generation",
        "branch": "Branch",
        "children": "Children",
        "partners": "Partners",
        "children_and_parentage": "Children and parentage",
        "and": " and ",
        "see": "See",
        "first_appearance": "first appearance in the genealogy",
        "view_profile": "View profile",
        "view_first_mention": "View first occurrence",
        "generation_navigation": "Generation navigation",
        "browse_generations": "Browse generations",
        "individual_profile": "Individual profile",
        "events": "Events",
        "notes": "Notes",
        "sources": "Sources",
        "references": "References",
        "repositories": "Repositories",
        "urls": "URLs",
        "media": "Media",
        "featured_image": "Featured image",
        "reproduction_unavailable": "reproduction unavailable",
        "full_page_reproduction": "Full-page reproduction:",
        "page_abbreviation": "p.",
        "author": "Author",
        "publication_date": "Publication date",
        "reference_family": "Reference family",
        "intermediate_model": "people in the intermediate model.",
        "skip_to_content": "Skip to main content",
        "couple_portraits": "Couple portraits",
        "portrait_of": "Portrait of",
        "document": "Document",
        "document_image_no_description": "Document image without a description",
        "see_reproduction": "View reproduction:",
        "document_reference": "Document reference",
        "role": "Role",
        "filiation": "parentage",
        "gramps_identifiers": "Gramps identifiers",
        "citation": "citation",
        "source": "source",
        "owner_person": "person",
        "owner_family": "family",
        "owner_event": "event",
        "owner_note": "note",
        "owner_media": "media",
        "owner_citation": "citation",
        "book_title_fallback": "Genealogical book",
    },
}


def label(model, key: str, *, default: str = "fr") -> str:
    """Return a translated renderer label for this model."""
    return _LABELS[model_book_language(model, default=default)].get(key, key)


def owner_label(model, owner_type: str, *, default: str = "fr") -> str:
    """Translate known record types and retain unknown types as written."""
    key = f"owner_{owner_type}"
    translated = label(model, key, default=default)
    return owner_type if translated == key else translated


def label_for_language(language: str, key: str) -> str:
    """Return a translated renderer label when only a language code is available."""
    return _LABELS.get(language, _LABELS["en"]).get(key, key)
