"""Stable, language-independent Gramps metadata names used by the plugin."""

BOOK_SCHEMA_VERSION = "0.2"

BOOK_PUBLICATION = "BOOK_PUBLICATION"
BOOK_PROFILE = "BOOK_PROFILE"
BOOK_EXCLUDE = "BOOK_EXCLUDE"
BOOK_FEATURED = "BOOK_FEATURED"

BOOK_TITLE = "BOOK_TITLE"
BOOK_SUBTITLE = "BOOK_SUBTITLE"
BOOK_INTRODUCTION = "BOOK_INTRODUCTION"
BOOK_DEDICATION = "BOOK_DEDICATION"
BOOK_AUTHOR = "BOOK_AUTHOR"
BOOK_PUBLICATION_DATE = "BOOK_PUBLICATION_DATE"
